### ISSUE TITLE
Requesting some clarification

### ISSUE THREAD

**Issue by maotora** [epsi-rns/epsi-rns.github.io#1]
Hello, great blog i learned something that i was never aware of.

In the setting ArchLinux page there is this code..

``` bash
iw dev
># # ip link set wlp0s3f3u2 up
># # iw dev wlp0s3f3u2 myessid
># wifi-menu
># ping google.com
```

In the line with `>#  iw dev wlp0s3f3u2 myessid`
what do i call `myessid` while i don't have it set yet? Or do i use the wireless `ssid` there?

Also when i do `ifconfig` i get my wifi device written as `wlo1` it looks way different from many devices i see in tutorials (including yours) am i really doing everything right or i'm missing something?

I could be asking a very dumb questions but please help. :) Thank you.

**Comment by epsi-rns** [comment]
Hello brother,
I must admit I don't the answer.

And I'm curious, how to open an issue in github.

Thank you
